spring:
  datasource:
    #   数据源基本配置
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/online_study_system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    #   禁用缓存
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/**
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml #指定全局配置文件的位置
  mapper-locations: classpath:mybatis/mapper/*.xml  #指定sql映射文件的位置

